      SUBROUTINE dtput
C
      REAL*8 DPARAM(10)
      REAL*8 EMIN,ESIZE,ASIZE,EMAX
C
      COMMON/RESOLV/EMIN,EMAX,ESIZE,ASIZE
      COMMON/DPARAM/DPARAM,NDTECT
C
      WRITE(13) EMIN,EMAX,ESIZE,ASIZE
      WRITE(13) NDTECT
      WRITE(13) (DPARAM(I),I=1,5)
      WRITE(13) (DPARAM(I),I=6,10)
C
      WRITE(66) EMIN,EMAX,ESIZE,ASIZE
      WRITE(66) NDTECT
      WRITE(66) (DPARAM(I),I=1,5)
      WRITE(66) (DPARAM(I),I=6,10)
      RETURN
      END
