      LOGICAL FUNCTION INSIDE(THETA,PHI)
C
C IS THE POINT AT THETA,PHI INSIDE THE DETECTOR?
C
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 DCIRC(4,4),DSEG(4,4),XDTECT(3)
      REAL*8 POINT(3)
      real*8 theta,phi
      LOGICAL INQUAD
C
      COMMON/DLIMIT/DCIRC,DSEG,XDTECT
C
C MAKE A UNIT VECTOR AT THETA,PHI
      CALL UNIT(THETA,PHI,POINT)
C IS THE VECTOR IN THE DETECTOR?
      INSIDE=INQUAD(POINT,XDTECT,DCIRC(1,1),DSEG(1,1),DCIRC(1,2),
     1        DSEG(1,2),DCIRC(1,3),DSEG(1,3),DCIRC(1,4),DSEG(1,4))
C
      RETURN
      END
